/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.github.jazzschmidt.spring.jsonvalidation

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.context.annotation.ComponentScan
import spock.lang.Specification

@SpringBootTest
class ApplicationTest extends Specification {

    @SpringBootApplication
    @ComponentScan("com.github.jazzschmidt.spring.jsonvalidation")
    protected static class SpringContext {}

    def "context starts"() {
        expect:
        true
    }

}
